/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as FoodSolutionsIndexRouteImport } from './routes/food-solutions.index'
import { Route as FoodSolutionsSlugRouteImport } from './routes/food-solutions.$slug'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as MachinesIndexRouteImport } from './routes/machines.index'
import { Route as MachinesSlugRouteImport } from './routes/machines.$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as MachinesCategoryCategoryRouteImport } from './routes/machines.category.$category'
import { Route as MachinesTypeTypeRouteImport } from './routes/machines.type.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodSolutionsIndexRoute = FoodSolutionsIndexRouteImport.update({
  id: '/food-solutions/',
  path: '/food-solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodSolutionsSlugRoute = FoodSolutionsSlugRouteImport.update({
  id: '/food-solutions/$slug',
  path: '/food-solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesSlugRoute = MachinesSlugRouteImport.update({
  id: '/machines/$slug',
  path: '/machines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesCategoryCategoryRoute =
  MachinesCategoryCategoryRouteImport.update({
    id: '/machines/category/$category',
    path: '/machines/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const MachinesTypeTypeRoute = MachinesTypeTypeRouteImport.update({
  id: '/machines/type/$type',
  path: '/machines/type/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/innovation': typeof InnovationRoute
  '/our-story': typeof OurStoryRoute
  '/resources': typeof ResourcesRoute
  '/food-solutions/$slug': typeof FoodSolutionsSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/machines/$slug': typeof MachinesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/food-solutions/': typeof FoodSolutionsIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/machines/': typeof MachinesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/machines/category/$category': typeof MachinesCategoryCategoryRoute
  '/machines/type/$type': typeof MachinesTypeTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/innovation': typeof InnovationRoute
  '/our-story': typeof OurStoryRoute
  '/resources': typeof ResourcesRoute
  '/food-solutions/$slug': typeof FoodSolutionsSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/machines/$slug': typeof MachinesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/food-solutions': typeof FoodSolutionsIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/machines': typeof MachinesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/machines/category/$category': typeof MachinesCategoryCategoryRoute
  '/machines/type/$type': typeof MachinesTypeTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/innovation': typeof InnovationRoute
  '/our-story': typeof OurStoryRoute
  '/resources': typeof ResourcesRoute
  '/food-solutions/$slug': typeof FoodSolutionsSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/machines/$slug': typeof MachinesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/food-solutions/': typeof FoodSolutionsIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/machines/': typeof MachinesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/machines/category/$category': typeof MachinesCategoryCategoryRoute
  '/machines/type/$type': typeof MachinesTypeTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/innovation'
    | '/our-story'
    | '/resources'
    | '/food-solutions/$slug'
    | '/industries/$slug'
    | '/machines/$slug'
    | '/solutions/$slug'
    | '/food-solutions/'
    | '/industries/'
    | '/machines/'
    | '/solutions/'
    | '/machines/category/$category'
    | '/machines/type/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/innovation'
    | '/our-story'
    | '/resources'
    | '/food-solutions/$slug'
    | '/industries/$slug'
    | '/machines/$slug'
    | '/solutions/$slug'
    | '/food-solutions'
    | '/industries'
    | '/machines'
    | '/solutions'
    | '/machines/category/$category'
    | '/machines/type/$type'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/innovation'
    | '/our-story'
    | '/resources'
    | '/food-solutions/$slug'
    | '/industries/$slug'
    | '/machines/$slug'
    | '/solutions/$slug'
    | '/food-solutions/'
    | '/industries/'
    | '/machines/'
    | '/solutions/'
    | '/machines/category/$category'
    | '/machines/type/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  InnovationRoute: typeof InnovationRoute
  OurStoryRoute: typeof OurStoryRoute
  ResourcesRoute: typeof ResourcesRoute
  FoodSolutionsSlugRoute: typeof FoodSolutionsSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  MachinesSlugRoute: typeof MachinesSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  FoodSolutionsIndexRoute: typeof FoodSolutionsIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  MachinesCategoryCategoryRoute: typeof MachinesCategoryCategoryRoute
  MachinesTypeTypeRoute: typeof MachinesTypeTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-solutions/': {
      id: '/food-solutions/'
      path: '/food-solutions'
      fullPath: '/food-solutions/'
      preLoaderRoute: typeof FoodSolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-solutions/$slug': {
      id: '/food-solutions/$slug'
      path: '/food-solutions/$slug'
      fullPath: '/food-solutions/$slug'
      preLoaderRoute: typeof FoodSolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$slug': {
      id: '/machines/$slug'
      path: '/machines/$slug'
      fullPath: '/machines/$slug'
      preLoaderRoute: typeof MachinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/category/$category': {
      id: '/machines/category/$category'
      path: '/machines/category/$category'
      fullPath: '/machines/category/$category'
      preLoaderRoute: typeof MachinesCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/type/$type': {
      id: '/machines/type/$type'
      path: '/machines/type/$type'
      fullPath: '/machines/type/$type'
      preLoaderRoute: typeof MachinesTypeTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  InnovationRoute: InnovationRoute,
  OurStoryRoute: OurStoryRoute,
  ResourcesRoute: ResourcesRoute,
  FoodSolutionsSlugRoute: FoodSolutionsSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  MachinesSlugRoute: MachinesSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  FoodSolutionsIndexRoute: FoodSolutionsIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  MachinesIndexRoute: MachinesIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  MachinesCategoryCategoryRoute: MachinesCategoryCategoryRoute,
  MachinesTypeTypeRoute: MachinesTypeTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
